name: .NET Desktop CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # ✅ Enables manual trigger from the GitHub UI

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Adjust for your version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore --configuration Release

    - name: Run format check
      run: dotnet format --verify-no-changes || echo "Formatting issues found"

    - name: Run tests
      run: dotnet test || echo "No tests found or some failed"
