name: .NET WPF Desktop CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Or 7.0.x if you're using 7

    - name: Install WindowsDesktop workload
      run: dotnet workload install windowsdesktop

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project (WPF Desktop)
      run: dotnet build CybersecurityAssistantApp.csproj --configuration Release --no-restore

    - name: Run format check
      run: dotnet format --verify-no-changes || echo "Formatting issues found"

    - name: Run tests (if any)
      run: dotnet test || echo "No tests found or some failed"
