name: Build CybersecurityAssistantApp

on:
  workflow_dispatch:  # 👈 Add this to enable manual runs
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 'latest'

      - name: Restore NuGet packages
        run: nuget restore CybersecurityAssistantApp.sln

      - name: Build solution
        run: msbuild CybersecurityAssistantApp.sln /p:Configuration=Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CybersecurityApp-Build
          path: '**/bin/Release/'
